name: cpp ci pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: kefir4iick
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: . 
          push: true  
          tags: ghcr.io/kefir4iick/mya:latest 

      - name: run tests in container
        run: |
          docker pull ghcr.io/kefir4iick/mya:latest
          docker run ghcr.io/kefir4iick/mya:latest

