name: cpp ci pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install clang
        run: brew install clang

      - name: build dioph.cpp
        run: clang++ -std=c++11 -c dioph.cpp -o dioph.o
      
      - name: build test.cpp
        run: clang++ -std=c++11 -c test.cpp -o test.o 
      
      - name: link
        run: clang++ dioph.o test.o -o test  

      - name: run tests
        run: ./test

